name = "tokenbel-wiki"
compatibility_date = "2026-07-31"

workers_dev = false
preview_urls = false

[assets]
directory = "./public"
not_found_handling = "404-page"

[[routes]]
pattern = "wiki.tokenbel.info/*"
zone_name = "tokenbel.info"

[[routes]]
pattern = "wiki.tokenbel.info"
custom_domain = true

[observability]
[observability.logs]
enabled = true
head_sampling_rate = 1
invocation_logs = true
persist = true

[observability.traces]
enabled = true

[placement]
mode = "smart"
