name = "tokenbel-wiki"
main = "worker.mjs"
compatibility_date = "2026-07-31"
preview_urls = true

[assets]
directory = "./public"
binding = "ASSETS"
run_worker_first = ["/about/*", "/guides/*", "/news/*", "/policies/*", "/statistics/*", "/tags/*"]
not_found_handling = "404-page"

[[routes]]
pattern = "wiki.tokenbel.info/*"
zone_name = "tokenbel.info"

[[routes]]
pattern = "wiki.tokenbel.info"
custom_domain = true

[observability]
[observability.logs]
enabled = true
head_sampling_rate = 1
invocation_logs = true
persist = true

[observability.traces]
enabled = true

[placement]
mode = "smart"
